services:
  server:
    image: nginx:mainline-alpine
    container_name: game-server
    restart: always
    tty: true
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default
    volumes:
      - ./nginx:/etc/nginx/conf.d/:ro
    depends_on:
      - backend
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: game-manager
    volumes:
      - ./game:/app
    env_file:
      - ./games/.env
    networks:
      - default
    command: sh -c  'chmod +x /app/start.app.sh && /app/start.app.sh'
    depends_on:
      - database
    ports:
      - '8000:8000'
  

  database:
    image: postgres:latest
    container_name: game-database
    restart: always
    env_file:
      - ./conf/.env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - default

networks:
  default:
    driver: bridge