"""Make start_at timezone aware

Revision ID: 2fde974582de
Revises: a58158c2779d
Create Date: 2025-06-09 02:05:04.387967

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "2fde974582de"
down_revision: Union[str, None] = "a58158c2779d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
